### ISSUE TITLE
[✨]: Congratulations for the work

### ISSUE THREAD

**Issue by leandromoh** [otterkit/otterkit-cobol#32]
Not a request feature at all. 
just a thanks for the working being done! 👏👏👏

**Comment by KTSnowy** [comment]
@leandromoh thank you so much!🦦

**Comment by GitMensch** [comment]
Out of interest (note: this issue should be moved to discussion in any case) @leandromoh Do you have an actual COBOL use? If yes do you need .NET or is GnuCOBOL (free software in stable working state) something relevant to try?

**Comment by leandromoh** [comment]
> Out of interest (note: this issue should be moved to discussion in any case) @leandromoh Do you have an actual COBOL use? If yes do you need .NET or is GnuCOBOL (free software in stable working state) something relevant to try?

I dont have any COBOL use currently @GitMensch; I am just a fan of the language.
