### ISSUE TITLE
[Core]: Defining an Embedded COBOL subset as a C replacement for systems programming (and why strict aliasing is broken)

### ISSUE THREAD

**Issue by KTSnowy** [otterkit/otterkit-cobol#35]
Let's start with the problem that I'm having (and attempting to solve). While trying to figure out some memory related details in our runtime, I realized that some COBOL features are impossible to implement in standard conforming C without invoking undefined behavior. More specifically, according to the rules in the C standard, it's not possible to implement COBOL's `REDEFINES` (unions) in C without invoking undefined behavior, and by extension most kinds of type punning is also prohibited.

I'll clarify what I mean by this, as this might also come as a surprise to other C developers. Both the C99 and C11 standards contain a footnote saying the following:

> If the member used to access the contents of a union object is not the same as the member last used to store a value in the object, the appropriate part of the object representation of the value is reinterpreted as an object representation in the new type as described in 6.2.6 (a process sometimes called "type punning"). This might be a trap representation.

Which at first makes it seem like C allows the kind of type punning we need to make COBOL's `REDEFINES` work. However, footnotes are specified in the foreword as non-normative:

> **In accordance with Part 3 of the ISO/IEC Directives, this foreword, the introduction, notes, footnotes, and examples are also for information only.**

Meaning that footnotes can't define normative behavior and should only clarify the existing normative text with additional information. No normative text exists in the C standard that specifies the kind of type punning described in the footnote. In fact, we have sections in the standard that contradict what is said in the footnote:

> **The value of at most one of the members can be stored in a union object at any time.** . . .

If the value of only one member can be stored in a union, then the value of the other members is non-existent (and reading from them would be UB). Nothing stops Clang and GCC from optimizing (currently or in the future) based on the assumption that union members, other than the very first written to, are in fact non-existent, so we risk undefined behavior here.

The other issue is, that even if we consider the footnote as normative (and resolve the conflicts), C's strict aliasing rules (in 6.5) would still prohibit us from accessing the same memory location as objects of different types:

> An object shall have its stored value accessed only by an lvalue expression that has one of the following types:
 — a type compatible with the effective type of the object,
 — a qualified version of a type compatible with the effective type of the object,
 — a type that is the signed or unsigned type corresponding to the effective type of the object,
 — a type that is the signed or unsigned type corresponding to a qualified version of the effective type of the object,
 — an aggregate or union type that includes one of the aforementioned types among its members (including, recursively, a member of a subaggregate or contained union), or
 — a character type.

So we have to assume that accessing (reading or writing) to the same memory location using different types is at best implementation-defined (`-fno-strict-aliasing`), and at worst **undefined behavior**. I'm not the first one having issues with how the standard defined these rules, as it turns out the Linux kernel is compiled with `-fno-strict-aliasing` for this same reason ([and generates a ton of type punning warnings when the flag is turned off](https://www.mail-archive.com/linux-btrfs@vger.kernel.org/msg01775.html)).

This strict aliasing issue is, of course, not only quite awful for any low-level systems programming, but also really bad for us because Standard COBOL does not have the same strict aliasing restrictions, and in fact, the ability to access the same memory location as different types is required in order to make `REDEFINES` (unions) work as specified by the standard.

As described in the section 13.18.44 of the COBOL23 standard:
> The REDEFINES clause allows the same computer storage area to be described by different data description entries.

And again a little further down, in the general rules for the clause:
> When the same storage area is defined by more than one data description entry, the data-name associated with any of those data description entries may be used to reference that storage area.

Being able to access the same memory location as different types is a requirement for Standard COBOL, and is at the same time a violation of Standard C's strict aliasing rules. So we can conclude that C as it currently is, cannot be used to implement COBOL's `REDEFINES` without invoking undefined or implementation-defined behavior (and by extension, C# unions have the same issue).

Some people have suggested using memcpy as a workaround to make type punning work in C, but this has several issues, one being that in order for this to work we need the compiler to be able to recognize the use of memcpy for type punning and optimize it out (not always possible, and risks more UB). If for some reason the call to memcpy is not optimized away and the call is actually executed then we'd be calling memcpy on overlapping memory, which is undefined behavior.

Also, using a memcpy-like function for type punning can cause undefined behavior **in COBOL**. As described in section 14.6.10:

> When the data items referenced by a sending and a receiving operand in any statement are identified as sharing either a part of or all of their storage areas, and the rules for the statement do not provide for a specific result in the following circumstances, then:
> 1) When the data items are not described by the same data description entry, the result of the statement is undefined.

I'd rather not have to deal with conflicting UB on both sides and strict aliasing weirdness, so I'm proposing a subset of Standard COBOL, that I'll be calling "Embedded COBOL", which consists only of language features that map as close to one-to-one as possible with freestanding standard C.

Please note that this won't be another dialect that Otterkit will directly support in addition to Standard COBOL, but rather a subset of Standard COBOL features that we'll be prioritizing (implementing first) in order to replace our existing C code as soon as possible.

I'll update this issue soon to start adding the C to COBOL feature mappings, let me know if anyone has any feature suggestions from C (that map to COBOL) that I should add to the list.

Tagging both @gabrielesilinic, and @TriAttack238. I need your feedback on this.

Also tagging @GitMensch. I don't think COBOL has any restrictions that would make this impossible, let me know if I'm wrong on this. Also, feel free to add any C features I should include that map directly to COBOL.

**Comment by KTSnowy** [comment]
### Arithmetic operations (C to COBOL feature mapping)

Probably the most basic set of operations a programming language can support are arithmetic operations. The following is how these operations are done in C:
```c
int a = 17;
int b = 25;
int res;

res = a + b; // addition
res = a - b; // subtraction
res = a * b; // multiplication
res = a / b; // division
```

Naturally, COBOL does not have standalone expressions in the same sense that C does (with a few exceptions). The following is how those same operations would be defined in COBOL by using the arithmetic statements:
```COBOL
*> In the data division
01 a binary-long value 17.
01 b binary-long value 25.
01 res binary-long.

*> In the procedure division.
add a to b giving res.
subtract a from b giving res.
multiply a by b giving res.
divide a by b giving res.
```
Alternatively, those can also be written using the compute statement. While the above statements are much closer to assembly in how they look (`add`, `sub`, ...), the following statement is closer to how arithmetic expressions look in C:
```COBOL
*> In the procedure division.
compute res = a + b.
compute res = a - b.
compute res = a * b.
compute res = a / b.
```
Since the the compute and arithmetic statements are identical in _behavior_, an optimizing COBOL compiler can "lower" all arithmetic statements into their compute equivalent, as long as the runtime behavior and result of execution still match what is specified by the standard for each statement.

**Comment by KTSnowy** [comment]
### Manual memory allocation (C to COBOL feature mapping)

An important feature of systems programming languages is the ability to manually request dynamic memory with a user-defined size, and then at a later point manually free the memory. In C this is done through library calls to malloc and free:
```C
// Returns a pointer to a block of at least 25 bytes.
void* ptr = malloc(25);
// Frees the memory pointed to by ptr.
free(ptr);
```
In COBOL, dynamic memory can be requested from the runtime by using the built-in `allocate` statement, and freed using the built-in `free` statement.
```cobol
*> In the data division
01 ptr pointer.

*> In the procedure division.
*> Returns a pointer to a block of at least 25 bytes.
allocate 25 characters returning ptr.
*> Frees the memory pointed to by ptr.
free ptr.
```
Alternatively, we can also allocate just enough memory to fit a certain data item. Please note that this syntax requires the data item to be described with the `based` clause.
```cobol
*> In the procedure division.
allocate b-item returning ptr.
```
In the above example, the returning phrase can be omitted if the pointer is not needed. The address of the b-item data item will be set to the address of the obtained storage.

**Comment by GitMensch** [comment]
### Re: mapping - and exception handling in general
A direct mapping of a COBOL _statement_ to anything will commonly only be possible as long as the user either doesn't have one of the most important things in the standard enabled or you handle it inline (which is not a direct one statement mapping any more): exception handling.
Don't forget that this may not only be enabled by `>> TURN` but also by `PERFORM` format-3 (exception-handling).

Often a direct mapping will also only work if the data-type matches a C data type, like `POINTER` or `BINARY-LONG` and if all data types involved match "enough".
Also: the use of a data-item itself may raise exceptions (especially `EC-BOUND` and `EC-DATA`).

### Re: `REDEFINE` (C union) and records

It is guaranteed that a union will have the size of its biggest element (`sizeof(some_union)`)  and that this will be used to allocate the union if you use that locally; and while the standard is explicit about "you can take out what you put in, but don't take a guarantee about taking out anything else" this is no problem for COBOL redefine, but about "if you put a `char` into a union containing all simple data types, getting out an int will be problematic".
If you allocate it with zeroed memory and you put a `char` in, you will still have a char plus zeroed memory in afterwards.
... that's _really_ no problem for COBOL rules.

Note that this is different to `struct`s as those will commonly include padding bytes (so no option to use this for records directly).
But there's a defined way that is guaranteed to work with COBOL rules: don't put the data-items into the struct but the amount of memory they need using `char[somesize]` and then set the data-item's storage to that memory. Using this you also don't need to think about possible undefined `union` access; you don't _need_ to use unions at all (but they still can make reading and debugging easier).

### Re: arithmetic operations
You can only use direct assignments if both parts have the same scale (you can adjust literals to match that) and if the result is guaranteed to fit completely into the target item.
For computations: those can also _only_ be used with a COBOL to C mapping if the target scale and size matches the maximum; as soon as rounding or truncation can apply you don't have any mapping that will work.

### Re: memory allocation
This is one of the spare things that _should_ work correctly with a direct mapping, if exception-handling is disabled.
For `ALLOCATE` and `FREE` the inline exception handling would be not that bad (testing a resulting pointer / the argument before the free; then handle, then take action).

**Comment by KTSnowy** [comment]
Hey, @GitMensch.

> But there's a defined way that is guaranteed to work with COBOL rules: don't put the data-items into the struct but the amount of memory they need using `char[somesize]` and then set the data-item's storage to that memory. Using this you also don't need to think about possible undefined `union` access; you don't need to use unions at all (but they still can make reading and debugging easier).

In C this will only work with `-fno-strict-aliasing`. Reason is the strict type aliasing rules. These rules are to make type-based alias analysis possible (optimization essentially), in which the compiler assumes that an access into a variable of one type is not modified by an access into a variable of a different type (access meaning reading or writing).

So lets say that we define the following in the data division:
```cobol
 01 Int32.
     05 ivalue binary-long.
 01 Float32 REDEFINES Int32.
     05 fvalue float-binary-32.
```

That has some real world applications, such as getting the IEEE representation of the float in an integer, and while it would be perfectly valid and free of undefined behavior in Standard COBOL, in C this is very prone to strict aliasing violations.

Due to strict aliasing, the compiler can assume that an access into ivalue is not modified by an access into fvalue. This can lead to either undefined behavior, or cases where the optimizer removes code that is actually needed.

Lets consider the following actions in a sort of pseudo assembly:
```asm
move ivalue, 0;      // write 0 into ivalue
move fvalue, 25.0;   // write 25.0 into fvalue
move rax,    ivalue; // write ivalue into rax
```
Type-based alias analysis in this case, can assume that our write into ivalue wasn't modified by our write into fvalue, so instead of loading ivalue into rax, the optimizer loads 0 into rax. Which then leads to the function returning 0, instead of the IEEE representation of 25.0 in an integer.

COBOL doesn't have strict aliasing so that's not an issue there, but this set of actions when done in C can lead to this behavior from the optimizer (without `-fno-strict-aliasing`).

Here's a snippet of C that demonstrates this behavior.
```C
#include <stdio.h>

int aliasing(float *fvalue, int *ivalue) {
    // move ivalue,   0; // write 0 into ivalue
    *ivalue = 0;
    // move fvalue,  25; // write 25.0 into fvalue
    *fvalue = 25.0f;            
    // move rax, ivalue; // write ivalue into rax
    return *ivalue;
}

int main(void) {
    // We'll use the same memory location:
    int int32 = 0;

    // Should print 0 here:
    printf("%d\n", int32);

    // Reinterpret (redefines) an int as a float:
    int32 = aliasing((float*)(&int32), &int32);

    // This prints 1103626240 on -O0 (correct)
    // but it prints 0 on -O2 (?????)
    printf("%d\n", int32);
}
```

It shows the correct result that we want on `-O0`, but on `-O2` it breaks completely and returns 0. If we look at the assembly output we can see why this happens.
```asm
aliasing: # @aliasing
  mov dword ptr [rsi], 0
  mov dword ptr [rdi], 1103626240
  xor eax, eax
  ret
```
The optimizer, through type-based alias analysis, assumed that our write into ivalue (0) wasn't modified by our write into fvalue (25.0). So instead of making another memory move, it decided to zero rax/eax (which returns 0, the value of ivalue before the write into fvalue).

If we rewrite that C snippet into COBOL (but using `REDEFINES`) and then compile back to C, it should have the same issues due to C's strict aliasing. Casting a `char*` (or `char[]`) into an `int*` or a `float*` (so we can store those there) is also a violation of these rules, and the optimizer is free to break more stuff if we do that.

**Comment by GitMensch** [comment]
> Due to strict aliasing, the compiler can assume that an access into ivalue is not modified by an access into fvalue.

Can it? I think not because in C you'd either have something like

```c
union sample {
   struct Int32 {
      int ivalue;
   }
   struct Float32 {
      float fvalue;
   }  
}
```

Any working C compiler **must** know that any access to one may change the other, because this is what unions do!

Otherwise you'd have to have something like

```c
  char data[4] = { 0 };
  char *Int32 = &data;
  int *ivalue = (int *)&data;
  char *Float32 = &data;
  float *fvalue = (float *)&data;
```

And as those are all _pointers_, a C compiler **cannot** make any assumptions about its use, and if, then it must assume that all access to any of those pointers will adjust the others.

> Casting a `char*` (or `char[]`) into an `int*` or a `float*` (so we can store those there) is also a violation of these rules, and the optimizer is free to break more stuff if we do that.

You possibly want to check the two samples above with different compilers and different optimization levels. I don't think that those create strange results, do they?

**Comment by gabrielesilinic** [comment]
@KTSnowy can we pretty please have a simpler syntax? COBOL may be cool but it's quite verbose, if we could make it better and faster to write we probably should, it's fine to take inspiration from COBOL but ot doesn't have to be cobol, also what about LLVM?

**Comment by KTSnowy** [comment]
@GitMensch, yeah the part of the C standard that says that we can take a different union member from the one last written to is only valid (defined behavior) in the context of the strict aliasing rules. Using a union to access the same memory address as both an int and a float is a violation of the rules, and the optimizer will still assume that both pointers don't alias each other.

Replacing the single int with the sample union will result in the same behavior. The program when compiled with `-O0` returns `0 \n 1103626240` (correct result), and when compiled with `-O2` it will return `0 \n 0` (broken result).
```c
#include <stdio.h>

union sample {
    struct Int32 {
        int ivalue;
    } Int32;
    struct Float32 {
        float fvalue;
    } Float32;
};

static inline int aliasing(float *fvalue, int *ivalue) {
    // move ivalue,   0; // write 0 into ivalue
    *ivalue = 0;
    // move fvalue,  25; // write 25.0 into fvalue
    *fvalue = 25.0f;            
    // move rax, ivalue; // write ivalue into rax
    return *ivalue;
}

int main(void) {
    // We'll use the same memory location:
    union sample storage = {0};

    // Should print 0 here:
    printf("%d\n", storage.Int32.ivalue);

    // Reinterpret (redefines) an int as a float:
    storage.Int32.ivalue = aliasing(
        &storage.Float32.fvalue, &storage.Int32.ivalue
    );

    // This prints 1103626240 on -O0 (correct)
    // but it prints 0 on -O2 (?????)
    printf("%d\n", storage.Int32.ivalue);
}
```
I tried adding static inline (result is the same without it) to make sure that it wasn't the function call that was making the result weird. This would hopefully force the compiler to inline everything and to use the pointers directly (as a union), instead of opaque pointers through a function call.

The optimizer in this case just deleted my assignment of `25.0f` into the float (assumed it wasn't needed), and decided to zero the register of the value being passed into the printf calls (It's what the `xor` is doing to the `esi` register, `rdi` is passing the string format). The resulting assembly is just passing zeroed registers into printf.
```asm
main: # @main
  push rbx
  lea rbx, [rip + .L.str]
  mov rdi, rbx
  xor esi, esi
  xor eax, eax
  call printf@PLT
  mov rdi, rbx
  xor esi, esi
  xor eax, eax
  call printf@PLT
  xor eax, eax
  pop rbx
  ret
.L.str:
  .asciz "%d\n"
```

I also tested with the `char[]` in the example you gave. The resulting assembly is the same as the one above, just zeroing the register of the value being passed to `printf`. 
```c
#include <stdio.h>

static inline int aliasing(float *fvalue, int *ivalue) {
    // move ivalue,   0; // write 0 into ivalue
    *ivalue = 0;
    // move fvalue,  25; // write 25.0 into fvalue
    *fvalue = 25.0f;            
    // move rax, ivalue; // write ivalue into rax
    return *ivalue;
}

int main(void) {
    // We'll use the same memory location:
    char data[4] = { 0 };
    char *Int32 = data;
    int *ivalue = (int *)data;
    char *Float32 = data;
    float *fvalue = (float *)data;

    // Should print 0 here:
    printf("%d\n", *ivalue);

    // Reinterpret (redefines) an int as a float:
    *ivalue = aliasing(
        fvalue, ivalue
    );

    // This prints 1103626240 on -O0 (correct)
    // but it prints 0 on -O2 (?????)
    printf("%d\n", *ivalue);
}
```

The only way to "fix" this is by passing `-fno-strict-aliasing`, which seems more like a temporary fix to me. At that point we're not writing C anymore, but a dialect without strict aliasing, one which other compilers are not required to support at all. This same behavior occurs on both Clang and GCC (on x86), when tested with both `-O0` (the correct result) and `-O2` (the incorrect result).

**Comment by GitMensch** [comment]
Checked with GCC Debian 10.2.1-6, the result is two times ´0`, even with ?`-O3 -fstrict-aliasing`. Same with the following compilers on wandbox.org: GCC 12, gcc HEAD 14.0.0 2023090, clang 15.0.7 and clang HEAD 18.0.0 - for all three given samples.

The only way to create an issue is to not compile the source as C but C++ (g++ instead of gcc raises the mentioned error with all three code variants). Are you sure you use `gcc` (and a testfile ending with .c)?

**Comment by KTSnowy** [comment]
> can we pretty please have a simpler syntax?

@gabrielesilinic, this is meant as a strict subset of Standard COBOL that we'd use to replace C in our native code. Not a different dialect, more like a coding guideline of which Standard COBOL features can be used in place of C features, to replace C in systems programming (COBOL can be low level enough for it to work nicely)

Due to standard C misbehaving when accessing the same memory location as different types, implementing certain COBOL features (without undefined behavior) is impossible in C.

**Comment by KTSnowy** [comment]
> Checked with GCC Debian 10.2.1-6, the result is two times ´0, even with ?-O3 -fstrict-aliasing`. Same with the following compilers on wandbox.org: GCC 12, gcc HEAD 14.0.0 2023090, clang 15.0.7 and clang HEAD 18.0.0 - for all three given samples.

@GitMensch, printing two times `0` is the incorrect result. After writing the `25.0f` into the float we should be getting one `0` and one `1103626240`. Also, strict aliasing is enabled by default, it's a standard C requirement.

**Comment by KTSnowy** [comment]
I'm compiling it with these options, and just switching the optimization levels. Same options on GCC.
```
clang -O0 -std=c17 -pedantic -Wall -Wextra -Werror -o test test.c
```

**Comment by KTSnowy** [comment]
Essentially the C compiler is optimizing our float assignment away (due to strict aliasing), which makes it result in two zeros. In Standard COBOL this shouldn't happen, the float should be assigned to the same memory location as the int and displayed back as an int, reinterpreting the IEEE bits from the float as an int32.

**Comment by KTSnowy** [comment]
@gabrielesilinic We could use LLVM though, compiling COBOL to LLVM IR. Making it actually native, without requiring a C# or C translation step (and then generating C# bindings to make it work nicely with it).

**Comment by GitMensch** [comment]
> printing two times `0` is the incorrect result. After writing the `25.0f` into the float we should be getting one `0` and one `1103626240`

it obviously is getting late for me... and you're correct only with lower optimization or `-fno-strict-aliasing` we get the expected result with all of those 3 test programs.

**Comment by KTSnowy** [comment]
> it obviously is getting late for me...

@GitMensch, sorry if this caused you to stay up late. We can continue tomorrow and see if we can find a solution for it if you'd like.

> and you're correct only with lower optimization or `-fno-strict-aliasing` we get the expected result with all of those 3 test programs.

I assume it's because the optimizations based on the strict aliasing rules are only enabled with `-O2` and `-O3` on both GCC and Clang. Disabling the optimizations, either with the `-fno-strict-aliasing` flag or a lower optimization level "fixes" the problem, but both of these aren't truly permanent or ideal fixes (output executable could be much slower).

It might be time to bring in LLVM into the project, if we can't fix this properly. We could then make it behave exactly how the standard requires, without any inherited weirdness from both the C# and C's specifications.

**Comment by KTSnowy** [comment]
After going through the LLVM docs I've noticed that their IR assumes that whatever language is being compiled has C-like semantics.

Which COBOL definitely doesn't have, so we'd be trying to fit COBOL into a C-like box. COBOL is a statement-heavy language, with no one-to-one mapping between it and C for a lot of those.

Another big issue is that LLVM doesn't provide any ABI (calling convention) compatibility, they expect every frontend to reimplement the ABI every time, for every platform. [Rust for example had to reimplement a huge amount of ABI code.](https://github.com/rust-lang/rust/tree/master/compiler/rustc_target/src/abi/call)

If we can solve both of these issues we could start using LLVM, or we could also look for an alternative backend.

**Comment by KTSnowy** [comment]
> I've noticed that their IR assumes that whatever language is being compiled has C-like semantics.

We need an IR that has COBOL semantics, because translating those semantics to C-like semantics is a huge pain. I might change this issue's purpose (and name) from a Standard COBOL subset, to a Standard COBOL intermediate representation.

**Comment by KTSnowy** [comment]
@GitMensch, closing this issue now, I'm creating a new one to explain the situation a bit better. This one focused too much on just C's strict aliasing and COBOL to C mappings, but that's not the whole story.
