### ISSUE TITLE
[Core Dev] Ordering of the Data Division clauses

### ISSUE THREAD

**Issue by KTSnowy** [otterkit/otterkit-cobol#4]
Alright so, while implementing the "IS EXTERNAL" clause for the data items I got a bit confused about the ordering of these clauses, mostly because IBM, Micro Focus and GnuCOBOL let you order those randomly (with some exceptions).

For example, all three implementations allow you to write the value clause before the picture clause, and the usage clause after the value clause.

But the standard defines it differently, the COBOL standard gives a very specific ordering for those (picture > usage > value). The standard's ordering is implied by the data description entry's format 1, the COBOL metalanguage format used there does not allow for any ordering, and this can be compared with the metalanguage format used for the "ON EXCEPTION" and "NOT ON EXCEPTION" (used on the call statement) which does allow the user to choose which one to write first.

One of the main goals of Otterkit COBOL is strictly following the standard as much as possible to avoid accidentally creating yet another dialect. But one issue with that it seems, is that Otterkit would be breaking compatibility with every other implementation.

I'm still in favor of strictly conforming to the standard though, rather than doing my own thing. I'm opening this issue in hopes to get feedback on this.

**Comment by KTSnowy** [comment]
Hey @GitMensch let me know if you have any feedback on this. This will break compatibility with COBOL code written with GnuCOBOL that doesn't have the same clause ordering as defined in the standard.

**Comment by vbcoen** [comment]
The practical way, would be implemented is to allow any order while scanning a line (up to the period) then process the details as needed.

**Comment by KTSnowy** [comment]
Hey @vbcoen, Simon corrected me on the GnuCOBOL forum. The standard does actually say that it can have any ordering (with some exceptions). I should have read that part more carefully.

> The practical way, would be implemented is to allow any order while scanning a line (up to the period) then process the details as needed.

You mean that the parser would get everything until the period, and then pause to check if the details are valid?

That could actually work, check the level number and data name, then put everything until the period into a List so that it can be checked.

I'm having trouble dealing with the possible lack of a period though. For example if ordering is mostly random then determining where the period should be is a little harder, if a user misses a period the parser needs to pick up the issue and display the appropriate error message.

**Comment by KTSnowy** [comment]
Alright, managed to fix this issue. Now the clauses can be used in any order like the standard's definition. So I'm closing this issue for now
